
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 21 15:15:38 EDT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class SymTable {
  /* terminals */
  public static final int LBRACKET = 7;
  public static final int ASSIGNMENT = 17;
  public static final int LPAREN = 3;
  public static final int INT = 22;
  public static final int MINUS = 10;
  public static final int STATIC = 29;
  public static final int RPAREN = 4;
  public static final int NOT = 14;
  public static final int SEMICOLON = 2;
  public static final int AND = 13;
  public static final int LESSTHAN = 12;
  public static final int COMMA = 16;
  public static final int CLASS = 27;
  public static final int PLUS = 9;
  public static final int MAIN = 33;
  public static final int IF = 18;
  public static final int THIS = 31;
  public static final int ID = 38;
  public static final int DOT = 15;
  public static final int EOF = 0;
  public static final int BOOLEAN = 23;
  public static final int RETURN = 21;
  public static final int RBRACKET = 8;
  public static final int TRUE = 25;
  public static final int NEW = 32;
  public static final int error = 1;
  public static final int VOID = 30;
  public static final int TIMES = 11;
  public static final int LBRACE = 5;
  public static final int ELSE = 19;
  public static final int WHILE = 20;
  public static final int PUBLIC = 28;
  public static final int RBRACE = 6;
  public static final int EXTENDS = 34;
  public static final int STRING = 24;
  public static final int FALSE = 26;
  public static final int PRINT = 36;
  public static final int LENGTH = 35;
  public static final int INT_LITERAL = 37;
}

